import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import WebsitesProjects from './templates/WebsitesProjects';
import AppProjects from './templates/AppProjects';
import ToolsProjects from './templates/ToolsProjects';
import HomeBanner from './templates/HomeBanner';
import AboutBanner from './templates/AboutBanner';

const Home = () => {

  return (
    <div>
      <Head>
        <title>Shivendra Saurav</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="top"></div>

      <HomeBanner/>
      

      <div className="projectsBanner" id="projects">
        <br/><br/>
        <h1 className="name">Projects</h1>
        <br/><br/>

        <AppProjects/>

        <WebsitesProjects />

        <ToolsProjects />

      </div>

      <AboutBanner/>

      <div id="cursor" className="cursor"></div>

    </div>
  )
}


export default Home;